mon_api_homepage:
    path:     /
    defaults: { _controller: MonApiBundle:Api:index }
mon_api_add:
    path:     /add
    defaults: { _controller: MonApiBundle:Api:add }
mon_api_edit:
    path:     /edit/{slug}
    defaults: { _controller: MonApiBundle:Api:add }
mon_api_delete:
    path:     /delete/{slug}
    defaults: { _controller: MonApiBundle:Api:delete }
mon_api_show:
    path:     /show/{slug}
    defaults: { _controller: MonApiBundle:Api:show }
mon_api_image:
    path:     /show/image/{image}
    defaults: { _controller: MonApiBundle:Api:showimage }
mon_api_search_empty:
    path:     /search/
    defaults: { _controller: MonApiBundle:Api:search }
mon_api_search_full:
    path:     /search/{categorie}/{ville}
    defaults: { _controller: MonApiBundle:Api:search }
recuperation_annonce:
    path:     /api/get/annonce/{annonce}
    defaults: { _controller:MonApiBundle:ApiRest:getannonce }
    methods:  [GET]
recuperation_annonce_ville:
    path:     /api/get/ville/{ville}
    defaults: { _controller:MonApiBundle:ApiRest:getville }
    methods:  [GET]
recuperation_annonce_categorie:
    path:     /api/get/categorie/{categorie}
    defaults: { _controller:MonApiBundle:ApiRest:getcategorie }
    methods:  [GET]
recuperation_annonce_categorie_ville:
    path:     /api/get/categorie/{categorie}/ville/{ville}
    defaults: { _controller:MonApiBundle:ApiRest:getcateville }
    methods:  [GET]
ajout_annonce_categorie:
    path:     /api/add/categorie/{categorie}
    defaults: { _controller:MonApiBundle:ApiRest:postcategorie }
    methods:  [POST]
ajout_annonce_ville:
    path:     /api/add/ville/{ville}
    defaults: { _controller:MonApiBundle:ApiRest:postville }
    methods:  [POST]
delete_annonce:
    path:     /api/delete/annonce/{annonce}
    defaults: { _controller:MonApiBundle:ApiRest:deleteannonce }
    methods:  [DELETE]